### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [t2er/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by t2er** [comment]
Added, you can use

**Comment by unixorn** [comment]
One more thing - would you consider renaming the repo to t2er-theme or something else less generic than zsh-theme?

Thanks!

**Comment by t2er** [comment]
no problem

**Comment by unixorn** [comment]
Thanks! Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/866
